//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgaChat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public int LanguageId { get; set; }
    
        public virtual ProgrammingLanguage ProgrammingLanguage { get; set; }
    }
}
